#!/bin/bash

FOLLOW_FLAG=""
if [[ $1 == "-f" ]]; then
  FOLLOW_FLAG="-f"
  shift
fi

CONTAINER="$1"

NAMES=$(docker inspect "$CONTAINER" | jq -r '.[].Name' | sed 's|^/||' | tr '\n' ',' | sed 's|,$||' )
printf "\e]1337;SetBadgeFormat=%s\a" $(echo -n "${NAMES}" | base64)
docker logs $FOLLOW_FLAG "$CONTAINER"
printf "\e]1337;SetBadgeFormat=%s\a" $(echo -n "" | base64)
