#!/bin/bash

NAMES=$(docker inspect $1 | jq -r '.[].Name' | sed 's|^/||' | tr '\n' ',' | sed 's|,$||' )
printf "\e]1337;SetBadgeFormat=%s\a" $(echo -n "${NAMES}" | base64)
docker logs "$1" 
printf "\e]1337;SetBadgeFormat=%s\a" $(echo -n "" | base64)
