#!/bin/bash

STATE_FILE="${HOME}/.task/.state"

COMMAND=/opt/homebrew/bin/task
if [ -f /usr/local/bin/task ]; then
    COMMAND=/usr/local/bin/task
fi

if [ -f /home/linuxbrew/.linuxbrew/bin/task ]; then
    COMMAND=/home/linuxbrew/.linuxbrew/bin/task
fi

${COMMAND} count +READY +ACTIVE > "${STATE_FILE}"
${COMMAND} count +READY -ACTIVE >> "${STATE_FILE}"

ACTIVE_TASKS=$(head -n 1 "${STATE_FILE}")
READY_TASKS=$(tail -n 1 "${STATE_FILE}")

echo "A: ${ACTIVE_TASKS} P: ${READY_TASKS}"
