#!/bin/sh

GIT_PAGER=cat
GIT_STATUS=$(git status --short | grep $1 | awk '{print $1}')

if [[ "${GIT_STATUS}" == "??" ]]; 
then
    if [[ -d $1 ]];
    then
        tree -L 2 -C $1
    else
        bat -n --color=always $1
    fi
fi

if [[ "${GIT_STATUS}" == "D" ]]; 
then
    echo "${BRIGHT}${YELLOW}$1${NORMAL} has been ${BRIGHT}${RED}DELETED${NORMAL}"
fi

if [[ "${GIT_STATUS}" == "M" ]]; 
then
    git diff --no-ext-diff --color=always -C $1 | head -200
fi