#!/bin/sh

FILE_OR_DIR="$*"

if [ -e "${FILE_OR_DIR}" ]; then
    if [ -f "${FILE_OR_DIR}" ]; then
        bat --color always "${FILE_OR_DIR}"
    else
        tree -C "${FILE_OR_DIR}" | head -200
    fi
else 
    echo "No preview for ${FILE_OR_DIR}"    
fi  