#!/bin/sh

# Input must be:
# <Simplified Human Status> <Filename>
# Example:
# Added somedir/some-file

file_to_preview=$(echo $* | awk '{$1=""; print $0}' | sed 's|^ ||g' | tr -d '"') # Drop the first argument (git status), drop leading spaces, drop wrapping double quotes

git_status=$(echo $* | awk '{print $1}')

if [[ "${git_status}" == "Added" ]]; 
then
    if [[ -d $file_to_preview ]];
    then
        tree -L 2 -C "$file_to_preview"
    else
        bat -n --color=always "$file_to_preview" 
    fi
fi

if [[ "${git_status}" == "Deleted" ]]; 
then
    echo "${BRIGHT}${YELLOW}$1${NORMAL} has been ${BRIGHT}${RED}DELETED${NORMAL}"
fi

if [[ "${git_status}" == "Modified" ]]; 
then
    git diff --no-ext-diff --color=always -C "$file_to_preview" | head -200
fi
