#!/bin/sh

GIT_PAGER=cat
GIT_STATUS=$(git status --short $1 | awk '{print $1}')

if [[ "${GIT_STATUS}" == "??" ]]; 
then
    if [[ -d $1 ]];
    then
        tree -L 2 -C $1
    else
        bat -n --color=always $1
    fi
else
    git diff --no-ext-diff --color=always -C $1 | head -200
fi