#!/bin/sh

update_temp_file_with_docs() {
    local directory=$1
    local temp_file=$2

    cd $directory

    for file in `ls -a`
    do
	[[ ! ${file} == ${HELP_SCRIPT} && -f ${file} ]] && {
            grep "#DOC#" $file >> ${temp_file}
	}
    done
}

HELP_SCRIPT=$(basename "$0")

SCRIPTS_DIR=$(dirname "$0")
BASE_DIR=$(dirname "${SCRIPTS_DIR}")

PATTERN=$(echo $* | sed 's/ /\.\*/g');

TEMP_FILE=$(mktemp)


update_temp_file_with_docs ${SCRIPTS_DIR} ${TEMP_FILE}

if [[ -d "${PERSONAL_CODE_ROOT}" ]]; then
  GO_BACK=$(pwd)
  cd ${PERSONAL_CODE_ROOT}

  for dir_name in `ls`;
  do
    if [[ -f "${PERSONAL_CODE_ROOT}/${dir_name}/.scripts" ]];
    then
      update_temp_file_with_docs ${PERSONAL_CODE_ROOT}/${dir_name}/scripts ${TEMP_FILE}
    fi
  done

  cd ${GO_BACK}
fi

ALIAS_DIR=${BASE_DIR}/.aliases
update_temp_file_with_docs ${ALIAS_DIR} ${TEMP_FILE}

printf "\n${BRIGHT}${GREEN}%-20s%-30s%s${NORMAL}\n" "Group" "Name" "Description"
[[ -s ${TEMP_FILE} ]] && {
    egrep -i "${PATTERN}" ${TEMP_FILE} | sed 's/.*#DOC# //' |  sort -u | awk 'BEGIN { FS = ";" } {gsub ("~EMP~", "\033[1;34;40m",$3); gsub ("~NORM~", "\033[0;37;40m",$3); printf "\033[1;36;40m%-20s\033[1;37;40m%-30s\033[0;37;40m%s\n", $1, $2, $3}'
}

echo

rm ${TEMP_FILE}
