#!/bin/bash

. .commons

SCRIPTS_DIR=`dirname $0`
ALIAS_DIR=${SCRIPTS_DIR}/..
HELP_SCRIPT=`basename $0`

cd ${SCRIPTS_DIR}

printf "\n${BRIGHT}${GREEN}%-20s\tDescription${NORMAL}\n" "Name"
for file in *
do
	[[ ! $file == ${HELP_SCRIPT} ]] && {
		DESCRIPTION=$(grep "#S#.*###" $file | sed 's/#S# \(.*\) ###/\1/' | sed 's/~EMP~/\\033\[1;34;40m/g' | sed 's/~NORM~/\\033\[0;37;40m/g')
		[[ ! -z ${DESCRIPTION} ]] && {
			printf "${BRIGHT}${BLUE}%-20s${NORMAL}\t${DESCRIPTION}\n" ${file}
			needDelimiter='Y'
		}
	}
done

[[ ${needDelimiter} == 'Y' ]] && printf '=================================================================================\n'

#grep "#A#" ${ALIAS_DIR}/.*aliases | sed 's/.*#A# //' | sort | awk 'BEGIN { FS = ";" }; {printf "\033[1;33m%-20s\033[0;37m\t%s\n", $1, $2}'
grep "#A#" ${ALIAS_DIR}/.*aliases | sed 's/.*#A# //' | sort | awk 'BEGIN { FS = ";" } {gsub ("~EMP~", "\033[1;34;40m",$2); gsub ("~NORM~", "\033[0;37;40m",$2); printf "\033[1;37;40m%-20s\033[0;37;40m\t%s\n", $1, $2}'


echo
