#!/bin/bash

HELP_SCRIPT=$(basename "$0")

SCRIPTS_DIR=$(dirname "$0")
BASE_DIR=$(dirname "${SCRIPTS_DIR}")
ALIAS_DIR=${BASE_DIR}/.aliases

PATTERN=$(echo $* | sed 's/ /\.\*/g');

cd ${SCRIPTS_DIR}

printf "\n${BRIGHT}${GREEN}%-20s\tDescription${NORMAL}\n" "Name"
for file in *
do
	[[ ! ${file} == ${HELP_SCRIPT} && -f ${file} ]] && {
		DESCRIPTION=$(grep "#S#.*###" $file | sed 's/#S# \(.*\) ###/\1/' | sed 's/~EMP~/\\033\[1;34;40m/g' | sed 's/~NORM~/\\033\[0;37;40m/g')
		[[ ! -z ${DESCRIPTION} ]] && {
			printf "${BRIGHT}${BLUE}%-20s${NORMAL}\t${DESCRIPTION}\n" ${file}
			needDelimiter='Y'
		}
	}
done

[[ ${needDelimiter} == 'Y' ]] && printf '=================================================================================\n'

grep "#A#" ${ALIAS_DIR}/.*aliases | egrep -i "${PATTERN}" | sort -u | sed 's/.*#A# //' | sort | awk 'BEGIN { FS = ";" } {gsub ("~EMP~", "\033[1;34;40m",$3); gsub ("~NORM~", "\033[0;37;40m",$3); printf "\033[1;36;40m%-20s\033[1;37;40m%-20s\033[0;37;40m\t%s\n", $1, $2, $3}' 


echo
