#!/bin/sh

omers_birthday=$(date -j -f '%Y-%m-%dT%H:%M:%S' "2023-07-16T00:00:00" +%s 2> /dev/null)
noams_8th_birthday=$(date -j -f '%Y-%m-%dT%H:%M:%S' "2023-09-21T00:00:00" +%s 2> /dev/null)
noams_9th_birthday=$(date -j -f '%Y-%m-%dT%H:%M:%S' "2024-09-21T00:00:00" +%s 2> /dev/null)
noams_12th_birthday=$(date -j -f '%Y-%m-%dT%H:%M:%S' "2027-09-21T00:00:00" +%s 2> /dev/null)

NOAM=3
OMER=20


function help {
    if [[ -z "${SCRIPT}" ]];
    then
        SCRIPT=`basename $0`
    fi
    printf "\n"
    printf "Usage:\n"
    printf "\t${SCRIPT} <day of week to start from>"
    printf "\n"
    printf "Examples:\n"
    printf "\t# Start from December 30th 2022\n"
    printf "\t${SCRIPT} 2022-12-30\n"
    printf "\n"
    exit 1
}

if [[ $# -ne 1 ]];
then
    printf "${BRIGHT}${RED}Missing start date!${NORMAL}\n"
    help
fi

# Input date in human-readable format
input_date=$1

# Validate if the input is a valid date
if ! date -jf "%Y-%m-%d" "$input_date" &> /dev/null; then
    echo "Invalid date format. Please use YYYY-MM-DD."
    exit 1
fi


# Get the day of the week for the input date (0 = Sunday, 6 = Saturday)
day_of_week=$(date -jf "%Y-%m-%d" "$input_date" +"%w")

# Calculate the number of days to the next Friday
days_to_friday=$(( (5 - day_of_week + 7) % 7))

# Loop to print the next 12 Fridays
for ((i=0; i<12; i++)); do
    # Calculate the date of the next Friday
    next_friday=$(date -jf "%Y-%m-%d" -v +"$days_to_friday"d "$input_date" +"%Y-%m-%d")
    
    next_sunday=$(date -jf "%Y-%m-%d" -v -5d "$next_friday" +"%Y-%m-%d")

    epoch_of_friday=$(date -j -f "%Y-%m-%d" "$next_friday" +%s)

    # Print the date of the next Friday
    if [[ $epoch_of_friday -ge $omers_birthday ]]; 
    then
        OMER=50
    fi
    if [[ $epoch_of_friday -ge $noams_8th_birthday ]]; 
    then
        NOAM=10
    fi
    if [[ $epoch_of_friday -ge $noams_9th_birthday ]]; 
    then
        NOAM=20
    fi
    if [[ $epoch_of_friday -ge $noams_12th_birthday ]]; 
    then
        NOAM=50
    fi    
    echo "t add +Personal +DmeiKis scheduled:${next_friday}+15h wait:${next_sunday}+8h description:\"50 םוכס - ${next_friday} - ךיראתל היאמל סיכ ימד\""
    echo "t add +Personal +DmeiKis scheduled:${next_friday}+15h wait:${next_sunday}+8h description:\"50 םוכס - ${next_friday} - ךיראתל רמועל סיכ ימד\""
    echo "t add +Personal +DmeiKis scheduled:${next_friday}+15h wait:${next_sunday}+8h description:\"10 םוכס - ${next_friday} - ךיראתל םעונל סיכ ימד\""

    # Move to the next week
    days_to_friday=$((days_to_friday + 7))
done
