#!/bin/sh 

#########
# USE_SHARED_HISTORY - 'y' if state for this container's should be shared with all other containers that define it the same
# NO_STATE_WARNING - 'y' if the user does not wish to get notified that there are state/output for this container
# WORKSPACE_NAME - A pre-defined name for the workspace, used as the container name and as the base directory for output and state.
# NAMESPACE - An optional context for the workspace, used as the base directory for the workspace.
#########

ALL_WORKSPACES_ROOT="${HOME}/.my-docker-envs"

function get_running_containers {
    echo $(docker ps | awk '{print $NF}' | grep "${WORKSPACE_NAME}" | wc -l)
}

function set_iterm_profile {
    if [[ -f "${HOME}/.iterm2/it2profile" ]]; then
        ${HOME}/.iterm2/it2profile -s "${1}" 
    fi
}

function attach_to_running_container {
    docker exec -it $(docker ps | grep "${1}" | awk '{print $1}') zsh
}

function launch_container {
    mkdir -p ${WORKSPACE_DIR}

    OTHER_PARAMS=$(echo $* | sed "s|WORKSPACE_DIR|${WORKSPACE_DIR}|g")

    docker run \
        -e TERM -e COLORTERM -e LC_ALL=C.UTF-8 \
        --workdir /root/ \
        -v ${WORK_DIR}:/root/workspace/ \
        -v ${HISTORY_DIR}:/root/.history/ \
        --env WORKSPACE_NAME=${WORKSPACE_NAME} \
        ${OTHER_PARAMS} ${CONTAINER_NAME} \
        -t -i --rm ${IMAGE} 
}

IMAGE=$1
shift

if [[ -z "${WORKSPACE_NAME}" ]];
then
    WORKSPACE_NAME=$(echo ${IMAGE} | tr ':' '_' | sed 's|.*/||')-$(date +%s)-${RANDOM}-${RANDOM}
    WORKSPACE_DIR="${ALL_WORKSPACES_ROOT}/${WORKSPACE_NAME}"
else
    CONTAINER_NAME=" --name ${WORKSPACE_NAME} "
    if [[ -n "${NAMESPACE}" ]];
    then
        WORKSPACE_DIR="${ALL_WORKSPACES_ROOT}/${NAMESPACE}/$(echo ${WORKSPACE_NAME} | tr 'A-Z ' 'a-z-')"
    else
        WORKSPACE_DIR="${ALL_WORKSPACES_ROOT}/$(echo ${WORKSPACE_NAME} | tr 'A-Z ' 'a-z-')"
    fi
fi

set_iterm_profile "${WORKSPACE_NAME}" 

WORK_DIR="${WORKSPACE_DIR}/workspace/"

if [[ "y" == "${USE_SHARED_HISTORY}" ]];
then
    HISTORY_DIR="${ALL_WORKSPACES_ROOT}/.shared.state/"
else
    HISTORY_DIR="${WORKSPACE_DIR}/.history/"
fi

if [[ $(get_running_containers) -gt 0 ]];
then
    attach_to_running_container "${WORKSPACE_NAME}"
else  
    launch_container $*
fi

if [[ $(get_running_containers) -eq 0 ]];
then
    let state_files="$(find ${WORKSPACE_DIR} -type f | grep -v '/.history/' | wc -l)"+0

    if [[ ${state_files} -eq 0 ]];
    then
        echo "Cleaning up workspace"
        rm -rf ${WORKSPACE_DIR}
    else
        if [[ -z "${NO_STATE_WARNING}" ]]; 
        then
            echo "Remember - you have ${state_files} files left under ${WORKSPACE_DIR}"
        fi
    fi
fi

if [[ -n "${NAMESPACE}" ]];
then
    NAMESPACE_DIR="${HOME}/.my-docker-envs/${NAMESPACE}"
    let namespace_files="$(find ${NAMESPACE_DIR} -type f | wc -l)"+0

    if [[ ${namespace_files} -eq 0 ]];
    then
        echo "Cleaning up namespace ${NAMESPACE_DIR}"
        echo rm -rf ${NAMESPACE_DIR}
    fi
fi

set_iterm_profile "Default"
