#!/bin/sh

if (($# != 4))
then
    echo "Usage:"
    echo "eks <workspace name> <aws profile> <aws region> <eks cluster name>"
    echo ""
    exit 1
fi

export WORKSPACE_NAME=$(echo $1 | tr ' ' '-')

dockerrunit eks:$(cat ${HOME}/.my-docker-images.release) \
    -v ${HOME}/.aws/:/root/.aws \
    -v WORKSPACE_DIR/.kube:/root/.kube \
    --env AWS_PROFILE=$2 \
    --env AWS_REGION=$3 \
    --env EKS_CLUSTER=$4 
