#!/bin/bash

###############################################################
#S# Shows ~EMP~running~NORM~ java processes                 ###
###############################################################

${JAVA_HOME}/bin/jps -mlv | grep -v sun.tools.jps.Jps | awk '\
	BEGIN {print ""}\
	{\
		first=$1; \
		$1=""; \
		printf "\033[31;1m %s \033[32m ", first; \
		\
		for(i = 1; i <= NF; i++) \
		{ \
			if (index($i,"-D") == 1 ) printf "\033[32;1m %s \033[0m", $i; \
			else if (index($i,"-X") == 1 ) printf "\033[33;1m %s \033[0m", $i; \
			else if (index($i,"-") == 1 ) printf "\033[35;1m %s \033[0m", $i; \
			else printf "\033[36;1m %s \033[0m", $i;\
		}\
		print "";\
	}\
	END {print ""}'
