#!/bin/sh

IMAGE="lua-5.4-env:$(cat ${HOME}/.my-docker-images.release)"

if [[ $# == 1 ]];
then
    cd $1
    export WORKSPACE_NAME="$(basename $(pwd))"
    export NO_STATE_WARNING="y"
    dockerrunit ${IMAGE} -v $(pwd):/root/proj/
else
    USE_SHARED_HISTORY=y dockerrunit ${IMAGE}
fi

