#!/bin/sh


if [[ $# -ne 1 ]]; 
then
    echo "No valid project path supplied!"
    exit 1
fi

echo "Openning project $1"


if [[ -f "$1/build.gradle" ]];
then 
    open -na "IntelliJ IDEA CE.app" --args $1
else
    /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code $1
fi

