#!/bin/sh

if [[ $# == 1 ]];
then
    cd $1
    export WORKSPACE_NAME="$(basename $(pwd))"
    export PERMANENT_WORKSPACE="y"
    USE_SHARED_STATE=y dockerrunit python-3.9-env:$(cat ${HOME}/.my-docker-images.release) -v $(pwd):/root/proj/
else
    USE_SHARED_STATE=y dockerrunit python-3.9-env:$(cat ${HOME}/.my-docker-images.release) 
fi

