#!/bin/zsh

#################################
# Requires 'switchaudio-osx': 
# brew install switchaudio-osx
#################################

source $(csitools -m)/aliases/.common.aliases

SwitchAudioSource -s "MacBook Pro Speakers" -t output
SwitchAudioSource -s "MacBook Pro Microphone" -t input

printf "${BRIGHT}${GREEN}Moving to Built-In Speakers/Microphone${NORMAL}\n"
