#!/bin/zsh

#################################
# Requires 'switchaudio-osx': 
# brew install switchaudio-osx
#################################

source $(csitools -m)/aliases/.common.aliases

SwitchAudioSource -s "External Headphones" -t output
SwitchAudioSource -s "External Microphone" -t input

printf "${BRIGHT}${GREEN}Moving to Microphone + HeadSets${NORMAL}\n"
