#!/bin/bash

AWK_COMMAND='\
		BEGIN\
		{\
	       		FS="|";\
       		}\
       		{\
			printf " %-35s\t| %s\n", $1, $2;\
		}'

. .commons

BASE_DIR=`dirname $0`

printf "\n${BLUE}${BRIGHT} %-35s\t| %s${NORMAL}\n" "Description" "Command"

VALUE=$(echo $* | sed 's/ /\.\*/g')
#VALUE=$(echo $* | sed 's/\(.\)/\1\.\*/g')

[[ $# -gt 0 ]] && {
	cat ${BASE_DIR}/snippets | grep -v '^#' | sort -f | awk "${AWK_COMMAND}" | egrep -i "${VALUE}" | sed 's/~PIPE~/|/g' | sed 's/~NL~/\'$'\n\t\t\t\t\t  /g' | egrep -i --color "${VALUE}|$"
	echo
	exit 0
}

cat ${BASE_DIR}/snippets | grep -v '^#' | sort -f | awk "${AWK_COMMAND}" | sed 's/~PIPE~/|/g' | sed 's/~NL~/\'$'\n\t\t\t\t\t  /g'

echo
